---
desktop_path: "{{ user_home }}/Desktop"
shortcuts:
  - name: terminal.desktop
    content: |
      [Desktop Entry]
      Name=Terminal
      Exec=ptyxis
      Icon=org.gnome.Ptyxis
      Type=Application
      Terminal=false
  - name: vscode.desktop
    content: |
      [Desktop Entry]
      Name=Visual Studio Code
      Exec=/snap/bin/code
      Icon=/snap/code/current/meta/gui/vscode.png
      Type=Application
      Terminal=false
  - name: bruno.desktop
    content: |
      [Desktop Entry]
      Name=Bruno
      Exec=bruno %U
      Terminal=false
      Type=Application
      Icon=/snap/bruno/current/meta/gui/icon.png
      StartupWMClass=Bruno
      MimeType=x-scheme-handler/bruno;
      Comment=Opensource API Client for Exploring and Testing APIs
      Categories=Development;
