---
- name: Ensure devasc can sudo without password
  copy:
    dest: "/etc/sudoers.d/{{ existing_user }}"
    content: "{{ existing_user }} ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'

- name: Ensure Desktop folder exists
  file:
    path: "{{ desktop_path }}"
    state: directory
    owner: "{{ existing_user }}"
    group: "{{ existing_user }}"
    mode: '0755'